### ISSUE TITLE
Verify that all mlf-core features work with default "main" branches.

### ISSUE THREAD

**Issue by Zethson** [mlf-core/mlf-core#139]
Github recently changed the default branch of newly created repositories to "main". git itself went for similar measures.
I myself reverted to `master`, because I am just so used to it with muscle memory.
Since mlf-core automates a lot with specific branch names we must verify that everything still works.
I verified the following questions for `master`, but not yet `main`.

Questions to answer:

1. Does the automatic repository creation still work?
2. Does automatic syncing (can also be triggered manually) still work? Can be tested by deliberately decreasing the template version in the `.mlf_core.yml` file
3. Is the documentation still pushed to the gh-pages branch when pushed to the main branch? I am pretty sure that this one will break, but maybe there are some synonyms going on behind the scenes?

If anything here breaks, please report and we can fix it.

**Comment by Zethson** [comment]
https://github.com/mlf-core/mlf-core/blob/master/mlf_core/create/templates/common_files/%7B%7Bcookiecutter.commonName%7D%7D/.github/workflows/publish_docs.yml#L33

**Comment by Imipenem** [comment]
> 1. Does the automatic repository creation still work?
> 2. Does automatic syncing (can also be triggered manually) still work? Can be tested by deliberately decreasing the template  version in the .mlf_core.yml file

Tested and with the fix in #163 it worked.
