### ISSUE TITLE
Track input data with md5

### ISSUE THREAD

**Issue by Zethson** [mlf-core/mlf-core#141]
We currently do not track that the input data is/was the same.

I suggest that we unify the input training data parameter into ``--input`` or ``--training-data`` and always compute the md5 of all files or something and log the obtained value into mlflow.
This part should be added into the general `mlf_core.py` part. The linter should also reflect this.

**Comment by Zethson** [comment]
![image](https://user-images.githubusercontent.com/21954664/104750891-f8532500-5754-11eb-80c3-7089764e20b6.png)

**Comment by Zethson** [comment]
@Emiller88 Just assigning it to you for now. If you want and have time you can tackle this after #220 .
But it's not urgent! So don't stress yourself, please.

**Comment by Emiller88** [comment]
Where do you want to track the md5 sums? And I'm guess this is more of an added mlf-core feature, not using [mlflow.log_artifacts](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_artifacts)?

**Comment by Zethson** [comment]
I want to track them with mlflow. I was thinking that every file that gets downloaded (E. G. Pytorch data loader) or supplied as input parameter should get its md5sum calculated and then this is logged with mlflow (not as artifact).
Alternatively, we log the data Uri like suggested in the slack post above?
I myself am not perfectly sure yet. Wednesday, 03 February 2021, 11:32PM +01:00 from Edmund Miller  notifications@github.com :

**Comment by Zethson** [comment]
@ggabernet and @KevinMenden any thoughts and ideas? Wishes?

**Comment by KevinMenden** [comment]
Hmm Not immediately, I will give it some though ... I'm thinking you might have to do this in the data loader because that's usually the only one that sees the original data. But I also haven't had a coffee yet so  :)

**Comment by Zethson** [comment]
@KevinMenden @Emiller88 yes exactly. This is what I had in mind as well.
There might just be many edge cases. Dataloaders downloading the data to somewhere. Downloading the data on the fly or accessing it from e.g. S3
We could force dataloaders at least to download to /data, but then we would need to ensure that the tensorboard logs are not in /data but somewhere else.

@Emiller88 let's start simple. For now we can just provide the functionality and then slowly see how we can use it while we are developing the use-cases. I would suggest that you add a function to our shiny new MLFCore object which given a single path (string not Path to keep it simple) or a list of paths calculates the MD5 sums and logs them.

**Comment by Emiller88** [comment]
@Zethson gotcha. That was what I was thinking as well. Do you want it just printed out or how do you want it logged into mlflow specifically? I've gotten the MD5_sum function from @KevinMenden nf-core module PR.

**Comment by Zethson** [comment]
Must be logged with mlflow

Please refer to https://www.mlflow.org/docs/latest/tracking.html

**Comment by KevinMenden** [comment]
> @Zethson gotcha. That was what I was thinking as well. Do you want it just printed out or how do you want it logged into mlflow specifically? I've gotten the MD5_sum function from @KevinMenden nf-core module PR.

(And I got it from the net :D )
