### ISSUE TITLE
Add a single page to ease way into mlf-core

### ISSUE THREAD

**Issue by Zethson** [mlf-core/mlf-core#159]
I feel like the complexity of mlf-core is quite high.

Maybe a one page intro, which can be easily read from top to bottom could introduce the issue, the solution and how the technical parts fit into each other.

I'll write up some draft bullet points soon and then we can discuss whether this would make sense and what should/should not be included.

**Comment by KevinMenden** [comment]
I think that would be really helpful :) 
Lowers the barrier to get started. Haven't had the time yet to really dig into it yet, but it's on my agenda.
When I do, I can write down notes about what might be good to mention.

**Comment by Zethson** [comment]
Not sure yet whether this should be part of the documentation or on the website under /tutorial
Maybe docs and /tutorial links to the docs page?

@Imipenem I would put this onto our agenda for the end of next week.

And yeah - let's collect what we think would be useful.

**Comment by Zethson** [comment]
All right, so my plan is:

1. Route mlf-core.com/tutorial to RTD/tutorial
2. Write a big disclaimer on the tutorial page that this is supposed to be a full single page tutorial and not meant to be as a reference. Reference = rest of the docs
3. Very small section on what this is about -> paraphrasing the abstract of the paper
4. Overview of mlf-core in very few sentences. Maybe even the overview figure here?
5. Quick listing of the involved technologies & forwarding people to read and learn about those on their respective tutorials first: Conda or Docker, MLflow
6. Installing & configuring mlf-core
7. Creating projects & making Docker container public & making the documentation public
9. How to develop projects & mlf-core lint
10. How to run projects with CPU, GPU, multiGPU & selecting between Docker and Conda
11. How to start the MLflow UI and how to explore the data
12. How to start Tensorboard if supported
13. How to serve a mlf-core model
14. How to contribute a developed model to the mlf-core community
15. Where and how to get help -> mlf-core Slack

What I absolutely don't want is to write also tutorials about Conda, Docker & MLflow. People should refer to their docs and not mine. Additionally, I don't want to split it up into several files. Just one fat tutorial.rst with headers to read from top to bottom. This is supposed to complement and not to replace the reference documentation of all commands.

Thoughts @KevinMenden @Imipenem ? Anything missing?

**Comment by Imipenem** [comment]
> Overview of mlf-core in very few sentences. Maybe even the overview figure here?

Yes, I'd include the overview figure here; especially for an overview it will make it a bit easier to get the main ideas/features of mlf-core.

> Quick listing of the involved technologies & forwarding people to read and learn about those on their respective tutorials first: Conda or Docker, MLflow

Maybe include GH Actions as well?

> Creating projects & making Docker container public & making the documentation public

Maybe add some short info here on which templates are available? Or just pick one and stick with it for the rest of the tutorial? Both options are valid, imo.

> How to develop projects & mlf-core lint

Maybe drop 1 -2 small words on sync here (you also mentioned it in 14. but it may also fit here in the "mlf-core project lifecycle" (?) and just express the main ideas of the mlf-core linter (the "general" linter section should be very short here but maybe one could write a bit more on the more "specific" linter)

> How to run projects with CPU, GPU, multiGPU & selecting between Docker and Conda

Maybe state that we would recommend to not jump in between those two but stick with one for a project (just a minor thing though)

> How to start the MLflow UI and how to explore the data

Maybe add one or two screenshots here so users can actually see what it will basically looks like?

Overall, I like the idea of a "one-pager". I would suggest though to make it a bit more "varied" to add some screenshots (or even GIFs for example for lint?), but that's just my personal preference.
And yeah, you should absolutely not write tutorials for docker etc. here, +1.
