### ISSUE TITLE
Remove package outdated query from linter (or exclude some packages)

### ISSUE THREAD

**Issue by Imipenem** [mlf-core/mlf-core#211]
**The Problem**

Currently, our mlf-core linter queries every required package for each template and complains/warns if any of those is not in the latest version.

I think we should remove this or exclude at least some packages from this linting check. Because some newer packages might have conflicts with others and this would result in failing docker container build etc. The linters warning could lead user to update this dependency, which may result in errors and may also cause more harm.

**The Solution**
Like mentioned above, either remove this completly or at least, exclude some packages

**Comment by Zethson** [comment]
Mhmm.
I am not sure.
Of course you cannot just increase the version blindly, but that's why it does not autoupdate them but makes you aware of new packages.
Dependabot with Conda would be another option, but that is not yet available.

I'll have to think more about that, but at the moment I am against removing it.

**Comment by Imipenem** [comment]
Ok fair, but this leads me to a question: What about introducing a `Info` section beside the already existing linting sections (passed, warned, failed)? And move this sort of "linting" into the info section?

**Comment by Zethson** [comment]
That's not a bad idea.
But it would also introduce "visual clutter" by making the linting output a little bit longer. Let's discuss this in Element soon.

**Comment by Zethson** [comment]
I'll close it for now. We may revisit this when we rewrite the linter.
