### ISSUE TITLE
Streamline linting Github Workflows

### ISSUE THREAD

**Issue by Zethson** [mlf-core/mlf-core#216]
**Is your feature request related to a problem? Please describe.**

Currently all of our linting workflows of the templates are in their own files. There's
run_flake8_linting.yml, run_bandit.yml and run_mlf_core_lint.yml 
Too many files and we're always setting up Python several times.

**Describe the solution you'd like**

What about a single lint.yml file that runs each of these (in parallel)?

**Comment by Zethson** [comment]
Maybe also one for you @Emiller88 if you like? Judging from what you're doing over at nf-core modules this should be very straight forward for you :)

**Comment by Emiller88** [comment]
I'd be down! I'd like to give it a go with mega linter or super linter or whatever their called first.

**Comment by Zethson** [comment]
Oh that's part of a way bigger adventure.
We discussed this already for cookietemple https://github.com/cookiejar/cookietemple/issues/576

Since the custom mlf-core lint is not available in any MegaLinter or SuperLinter I am not sure whether we should use those at all or just copy and paste what we currently have into a single lint.yml file?

CC @Imipenem Thoughts?

**Comment by Emiller88** [comment]
Oh my bad, first thing in the morning here and I read it while making coffee. Let me look into how things are done in a bit.

**Comment by Imipenem** [comment]
@Zethson , yeah I think for now we should use those linters we already have (flake8, mlfcore, bandit) and merge them into a single workflow. We can reevaluate it when we integrated MegaLinter into cookietemple.
