### ISSUE TITLE
Warning when training mlflow-pytorch 2.0.0

### ISSUE THREAD

**Issue by Zethson** [mlf-core/mlf-core#229]
`2021/02/03 19:07:05 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during autologging: float() argument must be a string or a number, not 'Accuracy'`

printed after every epoch!

**Comment by Imipenem** [comment]
Thats new I did not encountered this while I tested it.

**Comment by Zethson** [comment]
Only shows up when training with the GPU.
Will test cross platform later

**Comment by Imipenem** [comment]
@Zethson are u sure about that? I tested it on my laptop with no GPU only CPU and same result.

**Comment by Zethson** [comment]
Seems to be gone with my latest changes.
Please verify @Imipenem and close if not observed.
