### ISSUE TITLE
fix-artifact-paths should provide feedback

### ISSUE THREAD

**Issue by Emiller88** [mlf-core/mlf-core#231]
**Describe the bug**

Running fix-artifact-paths with no path throws

```TypeError: argument of type 'PosixPath' is not iterable```

**To Reproduce**

```mlf-core fix-artifact-paths
**Expected behavior**

Something along the lines of "Please provide a path"

**Comment by Zethson** [comment]
This one is one me ;)
Good find, thanks!

**Comment by Zethson** [comment]
https://github.com/mlf-core/mlf-core/commit/dbddfa5527c8cec22562586fe01e3e17f830b95a
