### ISSUE TITLE
Thinking about moving AUTHORS.rst into docs only

### ISSUE THREAD

**Issue by Zethson** [mlf-core/mlf-core#267]
Was in root before to give more visibility to the authors, but we have so many root level files by now that I am thinking about moving them into docs/ only

**Comment by Zethson** [comment]
Thoughts @Imipenem @Emiller88 ?

**Comment by Emiller88** [comment]
Go for it! What's the long term plan for having other templates? Will specific people take ownership of them? What's the max number?

**Comment by Zethson** [comment]
> Go for it! What's the long term plan for having other templates? Will specific people take ownership of them? What's the max number?

I would be happy to have one template per by MLflow supported machine learning library in Python and possibly templates for other by MLflow supported languages like R as well. 
Maximum number = anything that MLflow supports

> Will specific people take ownership of them?

I wouldn't mind if that happens, but there will need to be some common mlf-core standards that all templates adhere to.
If you're interested we can surely discuss that.

**Comment by Imipenem** [comment]
Fine with me
