### ISSUE TITLE
Expanding or removing .editorconfig

### ISSUE THREAD

**Issue by Zethson** [mlf-core/mlf-core#268]
Currently it is pretty minimal.
We should either go all out on it and define more code editor standards or remove it.

Thoughts @Imipenem ?

**Comment by Imipenem** [comment]
I would personally expanding it instead of removing. 
By doing so, if we see there are no more "sain" additions, we can still think about removing it.

**Comment by Zethson** [comment]
Got ideas for expansions?

**Comment by Imipenem** [comment]
Ad-hoc no, but I have to take a closer look at the options over the next days and write a list here

**Comment by Emiller88** [comment]
Is a CI check for editorconfig wrapped up in cookietemple lint? I think it's pretty good, for reference this is my root editorconfig
```
# http://editorconfig.org
root = true

[*]
end_of_line = lf
indent_size = 4
indent_style = space
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = false

[{Vagrant,Cap,Rake,Gem}file]
indent_size = 2

[*.{el,rb,cr,lua,y{a,}ml,json,toml,coffee,css,s{a,c}ss,styl,slim,{t,j}s{,x},jade,pug,html,{,z}sh}]
indent_size = 2

[*.go]
indent_style = tab

[{Makefile,gitconfig}]
indent_style = tab
```
So I think the current way covers just about everything.

**Comment by Zethson** [comment]
> Is a CI check for editorconfig wrapped up in cookietemple lint?

Is a CI check for editorconfig wrapped up in cookietemple lint?

No, cookietemple lint doesn't check whether the file exists nor its content.
