### ISSUE TITLE
Add create gif with Github support & screenshots for making Github Package public in the tutorial

### ISSUE THREAD

**Issue by Zethson** [mlf-core/mlf-core#275]
Feedback from @Imipenem 

Current gif in the README does not use GH and therefore should not be used.

**Comment by Emiller88** [comment]
I'll take care of this if I can use https://asciinema.org/, I don't know to make a gif from a terminal, but I'm willing to learn!

**Comment by Zethson** [comment]
@Emiller88 cool!
We were always using https://github.com/phw/peek . I can highly recommend it. It's amazing.

**Comment by Zethson** [comment]
@Emiller88 
I forgot to mention: We use https://ezgif.com/ to edit the gifs. We usually increase the speed and remove redundant frames. 

Also, it might be nice to have a gif of training a mlflow-pytorch model and then opening the MLflow UI. Just to show off!

**Comment by Zethson** [comment]
@Emiller88 do you have time for this until Friday? If not no biggy and I'll move it to 1.11.

**Comment by Emiller88** [comment]
I will have time for it Friday, after I'm done with exams in the next two days!

**Comment by Zethson** [comment]
@Imipenem we need the gif from you since it would look weird with a different terminal. Would be much appreciated if you could add it!

**Comment by Imipenem** [comment]
Sure!
