### ISSUE TITLE
CI matrix for templates

### ISSUE THREAD

**Issue by Emiller88** [mlf-core/mlf-core#286]
As I'm changing each of the CI's for the models thoughts on doing a matrix and filters like we did in nf-core modules? More DRY, and it'll only get worse with more templates.

https://github.com/nf-core/modules/blob/master/.github/workflows/pytest-workflow.yml

**Comment by Emiller88** [comment]
Just realized this was point 3 in #284 . Leaving it for tracking.

**Comment by Zethson** [comment]
@Emiller88 perfectly agree. I've always liked what you've done to our CI so far.
We will also hopefully release the new cookietemple template in ~ 2 weeks to DRY the mlf-core CI a little bit better.

But feel free to get creative already :)

**Comment by Zethson** [comment]
@Emiller88 feel free to close this if you don't have any additional ideas

**Comment by Emiller88** [comment]
The only thing I could think of is adding checks for editorconfig following up #268 on the new templates, and for the overall repo. But I think that can be a separate issue, let me know if you agree.

**Comment by Zethson** [comment]
@Emiller88 do you mean checks whether the file exists or what checks do you envision?

**Comment by Emiller88** [comment]
Checks that files follow the editorconfig.

**Comment by Zethson** [comment]
Ahh, I see.
Think that's not important at the moment. The Python scripts are already checked for flake8.

What could be more interesting is to add a pre-commit setup for flake8 and black for our templates.

**Comment by Emiller88** [comment]
Gotcha. I just realized why I also care about editorconfig is its way more common for people not to install it on their editors and then sneaks into the codebase. The other linters are way easier to remember to run.

Anyways, sure make an issue of it and put it in https://github.com/mlf-core/mlf-core/milestone/3 but I'm adding https://github.com/editorconfig-checker/editorconfig-checker.python :stuck_out_tongue:
