### ISSUE TITLE
MNIST dataset download failes with 503 using torchvision 0.8.2

### ISSUE THREAD

**Issue by Imipenem** [mlf-core/mlf-core#298]
**Describe the bug**

In our pytorch template, when trying to run a project with the MNIST dataset, it will fail to download with a 503 error. See https://github.com/pytorch/vision/issues/1938.

**To Reproduce**

1. Create mlf-core pytorch project
2. Push it to GH
3. See train WF fail

**Expected behavior**

Training should start and run without any errors with the downloaded MNIST dataset.

**Solution**
See https://github.com/pytorch/vision/issues/1938. We need to update torchvision to 0.9.0. However, this results in many package conflicts (mainly pytorch (which should be upgraded to 1.8.0), pycuda/cudatoolkit).

**Comment by Zethson** [comment]
@Imipenem if upgrading pytorch to 1.8 and torchvision to 0.9 suffices then let's do this

**Comment by Imipenem** [comment]
Y unfortunately it seems not 😩

**Comment by Zethson** [comment]
So we need to try to ugprade
Pytorch, torchvision and the cudatoolkit using the latest NVIDIA channel

**Comment by Imipenem** [comment]
Y I updated:
pytorch -> 1.8.0
torchvision -> 0.9.0
and pycuda -> 2020.1

it seems like now cudatoolkit needs to be updated as well as running it without cudetoolkit runs fine ;)

**Comment by Zethson** [comment]
> 
> 
> Y I updated:
> pytorch -> 1.8.0
> torchvision -> 0.9.0
> and pycuda -> 2020.1
> 
> it seems like now cudatoolkit needs to be updated as well as running it without cudetoolkit runs fine ;)

Ok. Please open a PR and I will test this on GPU tmrw

**Comment by Imipenem** [comment]
Its not fixed yet ;)

> Package cudatoolkit conflicts for:
pytorch::torchvision=0.9.0 -> cudatoolkit[version='>=10.1,<10.2|>=10.2,<10.3|>=11.1,<11.2']
nvidia|nvidia::cudatoolkit=11.2.72
nvidia::cudatoolkit=11.2.72

Appearantly , we cannot use latest version of cudatoolkit ;(

**Comment by Zethson** [comment]
Broken again.

**Comment by Zethson** [comment]
>  fmassa commented 4 days ago
> 
> The release of 0.9.1 is expected to be out in around 10 days


https://github.com/pytorch/vision/issues/3549#issuecomment-799600594
