### ISSUE TITLE
log_input_data not working

### ISSUE THREAD

**Issue by Zethson** [mlf-core/mlf-core#324]
Hi,

```
    @classmethod
    def get_md5_sums(cls, dir, md5_sums=None):
        """
        Recursively go through directories and subdirectories
        and generate tuples of (<file_path>, <md5sum>)
        returns: list of tuples
        """
        if not md5_sums:
            md5_sums = []
        elements = glob.glob(dir + "/*")
        for elem in elements:
            # if file, get md5 sum
            if os.path.isfile(elem):
                elem_md5 = cls.md5(elem)
                md5_sums.append((elem, elem_md5))
            # if directory, apply recursion
            if os.path.isdir(elem):
                md5_sums = cls.get_md5_sums(elem, md5_sums)
            else:
                continue
```

this method does not return anything. 

`mlflow.log_param("input_hash", input_data + "-" + input_hash)` later would also use the list then. However, you cannot append a list and a string.

@Emiller88 how was this supposed to work again?

**Comment by Emiller88** [comment]
Hmm, gonna need to rethink this one, maybe some insight from @KevinMenden

**Comment by KevinMenden** [comment]
Yes it should return the `md5_sums` list of course 😁 

We could also restructure this a bit and use `os.walk` instead of the recursion, might be easier to read.
I might draft a PR later today when I get around to to do it.
