### ISSUE TITLE
Switch from conda to mamba

### ISSUE THREAD

**Issue by Imipenem** [mlf-core/mlf-core#337]
**Is your feature request related to a problem? Please describe.**

Conda can be very slow and versions conflict output is just a mess and not usable.

**Describe the solution you would like**

There is an alternative called `mamba` (https://github.com/mamba-org/mamba).  We may consider heading over to mamba at some point in the future

**Comment by Zethson** [comment]
mamba really is impressively fast and pretty. However, I could not build a container with it when using an environment file that had Scanpy in it. It worked when manually installing it with member in the interactive container bash shell.

No idea what's going on.

CC https://github.com/h5py/h5py/issues/1880

**Comment by Imipenem** [comment]
@Zethson  out of curiosity: Does this "only" occur with scanpy as dependency? Or didn't u test it's furthermore?

**Comment by Zethson** [comment]
Likely with all that have h5py as a dependency. Already wasted too much time with this so I didn't test single packages.
